foodz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("web.urls",namespace="web")),
    path('manager/',include("manager.urls",namespace="manager")),
    path('restaurant/',include("restaurant.urls",namespace="restaurant")),
    path('dboy/',include("dboy.urls",namespace="dboy")),

]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

manager/urls.py
from django.urls import path
from manager import views

app_name = "manager"



urlpatterns = [
    path('', views.index, name="index"),
   
    path("store_category/", views.store_category, name="store_category"),
    path("delete_store_category/<int:id>/", views.delete_store_category, name="delete_store_category"),

    path("sliders/", views.sliders, name="sliders"),
    path("sliders/delete/<int:id>/", views.delete_slider, name="delete_slider"),

   path("offers/", views.offers, name="offers"),
   path("offers/delete/<int:pk>/", views.delete_offer, name="delete_offer"),

   path("stores/", views.add_store, name="store_list"),
   path("stores/delete/<int:id>/", views.delete_store, name="delete_store"),

     path("delivery-boys/", views.delivery_boys, name="dboylist"),

    path("delivery-boys/delete/<int:id>/", views.delete_delivery_boy, name="delete_delivery_boy"),

   path("customers/", views.customers, name="customers"),  
path("customers/delete/<int:id>/", views.delete_customer, name="delete_customer"),




]



  

web/urls.py
from django.urls import path
from web import views

app_name = "web"


urlpatterns = [
   path('', views.index, name="index"),   
   path('login/', views.login, name="login"),
   path('register/', views.register, name="register"),
   path('logout/', views.logout, name="logout"),
   path('restaurants/<int:id>/', views.restaurants, name="restaurants"),
   
   path('single_restaurant/<int:id>/', views.single_restaurant, name="single_restaurant"),
   path('single_restaurant/cart_add/<int:id>/', views.cart_add, name="cart_add"),
   path('single_restaurant/rest_cart_plus/<int:id>/', views.rest_cart_plus, name="rest_cart_plus"),
   path('single_restaurant/rest_cart_minus/<int:id>/', views.rest_cart_minus, name="rest_cart_minus"),



   path('cart/', views.cart, name="cart"),
   path('cart/cart_plus/<int:id>/', views.cart_plus, name="cart_plus"),
   path('cart/cart_minus/<int:id>/', views.cart_minus, name="cart_minus"),


   path('offers/', views.offers, name="offers"),
   path('offer/apply/<int:id>', views.offer_apply, name="offer_apply"),


   path('checkout/', views.checkout, name="checkout"),
   path('account/', views.account, name="account"),


   path('address/', views.address, name="address"),
   path('add_address/', views.add_address, name="add_address"),
   path('address/edit/<int:id>', views.edit_address, name="edit_address"),
   path('address/delete/<int:id>', views.delete_address, name="delete_address"),
   path('address/select/<int:id>', views.select_address, name="select_address"),

   path('place_order/', views.place_order, name="place_order"),

   path('orders/', views.orders, name="orders"),
   path('order_tracking/<int:id>', views.order_tracking, name="order_tracking"),
]

customer/models.py
from django.db import models

from users.models import User

from restaurant.models import Store, FoodItem





class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email



class Address(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    address = models.CharField(max_length=355)
    address_type = models.CharField(max_length=255)
    landmark = models.CharField(max_length=200)
    latitude = models.FloatField(null=True, blank=True) 
    longitude = models.FloatField(null=True, blank=True)
    appartment = models.CharField(max_length=255)  
    phone_number = models.CharField(max_length=15)
    
    is_selected = models.BooleanField(default=False)  

    class Meta:
        db_table = 'customer_address'
        verbose_name = 'address'
        verbose_name_plural = 'addresses'
        ordering = ['-id']

    def __str__(self):
        return self.customer.user.email

    def save(self, *args, **kwargs):
        if self.phone_number:
            # Store only digits, remove extra symbols like :" etc.
            self.phone_number = ''.join(filter(str.isdigit, self.phone_number))
        super().save(*args, **kwargs)


class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    qty = models.IntegerField()
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    amnt = models.FloatField()


    class Meta:
        db_table = 'customer_cart'
        verbose_name = 'cart'
        verbose_name_plural = 'carts'
        ordering = ['-id']


    def __str__(self):
        return self.product.name
    

class CartBill(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    offer_amnt = models.FloatField(default=0, null=True, blank=True)
    delivery_charge = models.FloatField(default=0)
    coupen_code = models.CharField(max_length=255, null=True, blank=True)


    class Meta:
        db_table = 'customer_cart_bill'
        verbose_name = 'cart bill'
        verbose_name_plural = 'cart bills'
        ordering = ['-id']


    def __str__(self):
        return self.customer.user.email
    


class Order(models.Model):
    STATUS_CHOICES = [
        ('PLACED', 'Placed'),
        ('ACCEPTED', 'Accepted'),
        ('OUT_FOR_DELIVERY', 'Out for Delivery'),
        ('COMPLETED', 'Delivered'),
       
    ]

    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    order_id = models.CharField(max_length=255)
    address = models.ForeignKey(Address, on_delete=models.CASCADE)
    sub_total = models.FloatField()
    total = models.FloatField()
    store = models.ForeignKey(Store, on_delete=models.CASCADE, null=True, blank=True)
    delivery_charge = models.IntegerField(default=0)
    delivery_boy = models.ForeignKey('dboy.DeliveryBoy', null=True, blank=True, on_delete=models.SET_NULL)

    
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='PLACED')

    class Meta:
        db_table = 'customer_order'
        ordering = ['-id']  


class OrderItem(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(FoodItem, on_delete=models.CASCADE)
    qty = models.IntegerField()
    store = models.ForeignKey(Store, on_delete=models.CASCADE)
    amnt = models.FloatField()
    

    class Meta:
        db_table = 'customer_order_item'
        verbose_name = 'order item'
        verbose_name_plural = 'order items'
        ordering = ['-id']


    def __str__(self):
        return self.customer.user.email
    

class Offer(models.Model):
    coupon_code = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    offer = models.IntegerField()
    is_percentage = models.BooleanField(default=False)


    class Meta:
        db_table = 'offer_table'
        verbose_name = 'offer'
        verbose_name_plural = 'offers'
        ordering = ['-id']


    def __str__(self):
        return self.coupon_code
    
    

  

dboy/models.py
from django.db import models


from django.db import models
from django.contrib.auth.models import User  # or your CustomUser model
from restaurant.models import Store


class DeliveryBoy(models.Model):
    email = models.EmailField(max_length=255, unique=True)
    password = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    phone = models.CharField(max_length=15, unique=True)
    address = models.TextField()


    class Meta:
        db_table = "delivery_boy"
        ordering = ['-id']

    def __str__(self):
        return self.name

# Create your models here.

manager/models.py
from django.db import models

from users.models import User

class Manager(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.email

restaurant/models.py
from django.db import models

from users.models import User   




class StoreCategory(models.Model):
    name = models.CharField(max_length=255)
    image = models.FileField(upload_to='category')

    class Meta:
        db_table = 'restaurant_store_categoy'
        verbose_name = 'store category'
        verbose_name_plural = 'store categories'
        ordering = ['-id']

    def __str__(self):
        return self.name
    

class Store(models.Model):
    email = models.EmailField(max_length=255, unique=True)
    password = models.CharField(max_length=255)
    name = models.CharField(max_length=256)
    tagline = models.CharField(max_length=256)
    categories = models.ManyToManyField(StoreCategory, related_name="stores")
    image = models.FileField(upload_to='store')
    rating = models.FloatField()
    time = models.IntegerField()
    offer = models.CharField(max_length=255)


    class Meta:
        db_table = 'restaurant_store'
        verbose_name = 'store'
        verbose_name_plural = 'stores'
        ordering = ['-id']


    def __str__(self):
        return self.name
    


class Slider(models.Model):
    name = models.CharField(max_length=255)
    image = models.FileField(upload_to='slide')
    store = models.ForeignKey(Store, on_delete=models.CASCADE)


    class Meta:
        db_table = 'restaurant_slider'
        verbose_name = 'slider'
        verbose_name_plural = 'sliders'
        ordering = ['-id']


    def __str__(self):
        return self.name
    


    


class FoodCategory(models.Model):
    name = models.CharField(max_length=255) 
    store = models.ForeignKey(Store, on_delete=models.CASCADE) 


    class Meta:
        db_table = 'food_category'
        verbose_name = 'food category'
        verbose_name_plural = 'food categories'
        ordering = ['id']


    def __str__(self):
        return self.name
    



class FoodItem(models.Model):
    name = models.CharField(max_length=255)
    is_veg = models.BooleanField(default=False)
    price = models.IntegerField()
    image = models.FileField(upload_to='fooditems')
    categry = models.ForeignKey(FoodCategory, on_delete=models.CASCADE, related_name='fooditem')


    class Meta:
        db_table = 'food_item'
        verbose_name = 'food item'
        verbose_name_plural = 'food items'
        ordering = ['id']


    def __str__(self):
        return self.name

customer/views.py
from django.shortcuts import render

# Create your views here.

manager/views.py
from django.shortcuts import render, reverse, get_object_or_404 , redirect
from django.http.response import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from restaurant.models import *

from .forms import StoreCategoryForm
from django.contrib import messages
from manager.forms import *
from customer.models import *



def index(request):
    instances = Order.objects.all()
    orders = instances.count()
    stores = Store.objects.count()
    customers = Customer.objects.count()
    delivery_boys = DeliveryBoy.objects.count()

    # ✅ calculate 6% commission only on completed orders
    earnings = 0
    for order in instances:
        if order.status == "COMPLETED":   # correct status
            earnings += (order.total * 0.06)   # 6% cut

    context = {
        "instances": instances,
        "orders": orders,
        "stores": stores,
        "customers": customers,
        "delivery_boys": delivery_boys,
        "earnings": round(earnings, 2),  
    }
    return render(request, 'manager/index.html', context)


def order_list(request):
    orders = Order.objects.select_related("customer", "store", "address", "delivery_boy") \
                          .prefetch_related("orderitem_set")

    context = {
        "orders": orders
    }
    return render(request, "manager/index.html", context)
        

@login_required(login_url='/manager/login')
def store_category(request):
    if request.method == "POST":
        form = StoreCategoryForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("manager:store_category")  
    else:
        form = StoreCategoryForm()

    instances = StoreCategory.objects.all()

    context = {
        "form": form,
        "instances": instances
    }
    return render(request, "manager/store_categories.html", context)

def delete_store_category(request, id):
    category = get_object_or_404(StoreCategory, id=id)
    category.delete()
    messages.success(request, "Store category deleted successfully.")
    return redirect("manager:store_category")

def sliders(request):
    if request.method == "POST":
        form = SliderForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("manager:sliders")  
    else:
        form = SliderForm()

    instances = Slider.objects.all()
    return render(request, "manager/sliders.html", {"form": form, "instances": instances})

def delete_slider(request, id):
    slider = get_object_or_404(Slider, id=id)
    slider.delete()
    return redirect("manager:sliders")


def offers(request):
    if request.method == "POST":
        form = OfferForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, "Offer added successfully.")
            return redirect("manager:offers")
    else:
        form = OfferForm()

    instances = Offer.objects.all()
    return render(request, "manager/offers.html", {
        "form": form,
        "instances": instances,
    })


def delete_offer(request, pk):
    offer = get_object_or_404(Offer, pk=pk)
    offer.delete()
    messages.success(request, "Offer deleted successfully.")
    return redirect("manager:offers")



def add_store(request):
    if request.method == "POST":
        form = StoreForm(request.POST, request.FILES)
        if form.is_valid():
            store = form.save()
            return redirect("manager:store_list")  
    else:
        form = StoreForm()

    stores = Store.objects.all()
    return render(request, "manager/store_list.html", {"form": form, "stores": stores})


def delete_store(request, id):
    store = get_object_or_404(Store, id=id)
    store.delete()
    return redirect("manager:store_list")


def delivery_boys(request):
    if request.method == "POST":
        form = DeliveryBoyForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("manager:dboylist")
    else:
        form = DeliveryBoyForm()

    delivery_boys = DeliveryBoy.objects.all()

    context = {
        "form": form,
        "delivery_boys": delivery_boys,
    }
    return render(request, "manager/dboylist.html", context = context)


def delete_delivery_boy(request, id):
    delivery_boy = get_object_or_404(DeliveryBoy, id=id)
    delivery_boy.delete()
    return redirect("manager:dboylist")


def customers(request):
    customers = Customer.objects.select_related("user").all()
    return render(request, "manager/customers.html", {"customers": customers})


def delete_customer(request, id):
    customer = get_object_or_404(Customer, id=id)
    user = customer.user
    customer.delete()
    user.delete()
    messages.success(request, "Customer and user account deleted successfully!")
    return redirect("manager:customers")

templates/manager/sliders.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin Panel</title>
    {% load widget_tweaks %}
{% load static %}
    <!-- Tailwind CSS CDN -->
    <script src="https://cdn.tailwindcss.com"></script>

    <!-- Font Awesome CDN -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

    <!-- Google Fonts: Inter -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">

    <style>
        /* General Styles */
        body {
            font-family: 'Inter', sans-serif;
            background-color: #f8fafc;
            /* bg-slate-50 */
        }

        /* Custom scrollbar for better aesthetics */
        ::-webkit-scrollbar {
            width: 6px;
            height: 6px;
        }

        ::-webkit-scrollbar-track {
            background: #f1f1f1;
            border-radius: 10px;
        }

        ::-webkit-scrollbar-thumb {
            background: #cbd5e1;
            border-radius: 10px;
        }

        ::-webkit-scrollbar-thumb:hover {
            background: #94a3b8;
        }

        /* Common sticky header for tables */
        .table-sticky-header thead th {
            position: sticky;
            top: 0;
            z-index: 10;
        }
    </style>
</head>

<body class="text-slate-800">

    <div class="flex min-h-screen">
        <!-- Sidebar -->
        <aside id="sidebar"
            class="bg-slate-800 text-slate-100 w-64 fixed top-0 left-0 h-full z-40 lg:translate-x-0 -translate-x-full transition-transform duration-300 ease-in-out border-r border-slate-700 flex flex-col">
            <div class="flex-grow">
                <div class="py-2 flex justify-center w-full">
                    <div class="p-2 rounded-lg  text-center justify-center flex">
                      <img src="{% static 'web/images/logo.png' %}" alt="logo" class="w-20">
                    </div>
                   
                </div>
                <nav class="mt-6">
                    <ul>
                        <li><a href="{% url 'manager:index' %}"
                                class="flex items-center gap-4 px-6 py-3 text-slate-300 hover:bg-slate-700 hover:text-white transition-all duration-300 ease-in-out"><i
                                    class="fa-solid fa-chart-line  w-5 text-center"></i><span>Overview</span></a></li>
                        <li><a href="{% url 'manager:store_category' %}"
                                class="flex items-center gap-4 px-6 py-3 text-slate-300 hover:bg-slate-700 hover:text-white transition-all duration-300 ease-in-out"><i
                                    class="fas fa-list w-5 text-center"></i><span>Store Category</span></a></li>
                        <li><a href="{% url 'manager:sliders' %}"
                                class="flex items-center gap-4 px-6 py-3 text-slate-300 hover:bg-slate-700 hover:text-white transition-all duration-300 ease-in-out"><i
                                    class="fas fa-sliders-h w-5 text-center"></i><span>Sliders</span></a></li>
                        <li><a href="{% url 'manager:offers' %}"
                                class="flex items-center gap-4 px-6 py-3 text-slate-300 hover:bg-slate-700 hover:text-white transition-all duration-300 ease-in-out"><i
                                    class="fas fa-tag w-5 text-center"></i><span>Offers</span></a></li>
                        <li><a href="{% url 'manager:store_list' %}"
                                class="flex items-center gap-4 px-6 py-3 text-slate-300 hover:bg-slate-700 hover:text-white transition-all duration-300 ease-in-out"><i
                                    class="fas fa-store w-5 text-center"></i><span>Add Restaurants</span></a></li>
                        <li><a href="{% url 'manager:dboylist' %}"
                                class="flex items-center gap-4 px-6 py-3 text-slate-300 hover:bg-slate-700 hover:text-white transition-all duration-300 ease-in-out"><i
                                    class="fas fa-motorcycle w-5 text-center"></i><span>Add Delivery Boys</span></a>
                        </li>
                                                <li><a href="{% url 'manager:customers' %}" class="flex items-center gap-4 px-6 py-3 text-slate-300 hover:bg-slate-700 hover:text-white transition-all duration-300 ease-in-out"><i class="fa-solid fa-users w-5 text-center"></i><span>Customers</span></a></li>
                    </ul>
                </nav>
            </div>
            <!-- Logout Button -->
            <div class="p-4 border-t border-slate-700">
                <a href="{% url 'web:logout' %}"
                    class="flex items-center gap-4 px-4 py-3 text-slate-300 hover:bg-slate-700 hover:text-white transition-all duration-300 ease-in-out rounded-lg">
                    <i class="fas fa-sign-out-alt w-5 text-center"></i>
                    <span>Logout</span>
                </a>
            </div>
        </aside>

        <!-- Main Content -->
        <div id="main-content" class="flex-1 lg:pl-64 transition-all duration-300 ease-in-out">
            <!-- Top Navigation Bar -->
            <header class="bg-white/80 backdrop-blur-lg sticky top-0 z-30 shadow-sm">
                <div class="flex items-center justify-between p-4 border-b border-slate-200/80">
                    <div class="flex items-center gap-4">
                        <button id="hamburger-btn"
                            class="lg:hidden text-slate-600 hover:text-cyan-500 transition-colors duration-300 ease-in-out">
                            <i class="fas fa-bars"></i>
                        </button>
                        <h2 class="text-2xl font-semibold text-slate-800">Manager Dashboard</h2>
                    </div>

                </div>
            </header>

            <main class="p-4 sm:p-6 space-y-6">
                <!-- Stat Cards -->
            

                <!-- Table Section -->
                <section class="bg-white p-6 rounded-2xl shadow-sm">
    <!-- Add new slider -->
    <div class="mb-6">
        <div class="items-center mb-4 flex justify-between">
            <h3 class="text-xl font-semibold text-slate-700">Add New Sliders</h3>
        </div>
        <form method="post" enctype="multipart/form-data" 
      class="bg-white p-6 rounded-2xl border space-y-6 grid md:grid-cols-4 sm:grid-cols-2 grid-cols-1 gap-6">
    {% csrf_token %}
    
    <!-- Slider Name -->
    <div>
        <label for="id_name" class="block text-sm font-medium text-slate-700 mb-1">
            Slider Name
        </label>
        {{ form.name|add_class:"w-full p-2 border border-slate-300 rounded-lg focus:ring focus:ring-blue-200" }}
    </div>

    <!-- Slider Image -->
    <div>
        <label for="id_image" class="block text-sm font-medium text-slate-700 mb-1">
            Slider Image
        </label>
        {{ form.image|add_class:"w-full p-2 border border-slate-300 rounded-lg focus:ring focus:ring-blue-200" }}
    </div>

    <!-- Store -->
    <div>
        <label for="id_store" class="block text-sm font-medium text-slate-700 mb-1">
            Store
        </label>
        {{ form.store|add_class:"w-full p-2 border border-slate-300 rounded-lg focus:ring focus:ring-blue-200" }}
    </div>

    <!-- Submit -->
    <div>
        <button type="submit" 
                class="w-full md:w-auto mt-6 px-6 py-2  text-white rounded-lg shadow hover:bg-[#151572] bg-[#1a1a75] transition">
            Add Slider
        </button>
    </div>
</form>

    </div>

    <!-- Show current sliders -->
    <div>
        <div class="items-center mb-4 flex justify-between">
            <h3 class="text-xl font-semibold text-slate-700">Current Sliders</h3>
        </div>
        <div class="overflow-x-auto">
            <table class="w-full text-sm text-left text-slate-500">
                <thead class="text-xs text-slate-700 uppercase bg-slate-200">
                    <tr>
                        <th class="px-6 py-3">SI NO</th>
                        <th class="px-6 py-3">Slider Name</th>
                        <th class="px-6 py-3">Store</th>
                        <th class="px-6 py-3">Slider Image</th>
                        <th class="px-6 py-3">Action</th>
                    </tr>
                </thead>
                <tbody>
                    {% for slider in instances %}
                    <tr class="border-b">
                        <td class="px-6 py-3">{{ forloop.counter }}</td>
                        <td class="px-6 py-3">{{ slider.name }}</td>
                        <td class="px-6 py-3">{{ slider.store.name }}</td>
                        <td class="px-6 py-3">
                            <img src="{{ slider.image.url }}" class="h-12 rounded" />
                        </td>
                        <td class="px-6 py-3">
                            <a href="{% url 'manager:delete_slider' slider.id %}" 
                               class="px-3 py-1  text-red-800 rounded-lg hover:underline">
                                Delete
                            </a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5" class="text-center py-4">No sliders added yet</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>


            </main>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const sidebar = document.getElementById('sidebar');
            const hamburgerBtn = document.getElementById('hamburger-btn');
            const mainContent = document.getElementById('main-content');

            // Sidebar toggle functionality
            const toggleSidebar = () => {
                sidebar.classList.toggle('-translate-x-full');
            };

            if (hamburgerBtn) {
                hamburgerBtn.addEventListener('click', toggleSidebar);
            }

            // No need to initialize Lucide icons anymore
        });
    </script>
</body>

</html>