foodz/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("web.urls",namespace="web")),
    path('manager/',include("manager.urls",namespace="manager")),
    path('restaurant/',include("restaurant.urls",namespace="restaurant")),
    path('dboy/',include("dboy.urls",namespace="dboy")),

]


if settings.DEBUG:
    urlpatterns += (
        static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) +
        static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
)

manager/urls.py
from django.urls import path
from manager import views

app_name = "manager"



urlpatterns = [
    path('', views.index, name="index"),
   
    path("store_category/", views.store_category, name="store_category"),
    path("delete_store_category/<int:id>/", views.delete_store_category, name="delete_store_category"),

    path("sliders/", views.sliders, name="sliders"),
    path("sliders/delete/<int:id>/", views.delete_slider, name="delete_slider"),

   path("offers/", views.offers, name="offers"),
   path("offers/delete/<int:pk>/", views.delete_offer, name="delete_offer"),

   path("stores/", views.add_store, name="store_list"),
   path("stores/delete/<int:id>/", views.delete_store, name="delete_store"),

     path("delivery-boys/", views.delivery_boys, name="dboylist"),

    path("delivery-boys/delete/<int:id>/", views.delete_delivery_boy, name="delete_delivery_boy"),

   path("customers/", views.customers, name="customers"),  
path("customers/delete/<int:id>/", views.delete_customer, name="delete_customer"),




]



  

web/urls.py
from django.urls import path
from web import views

app_name = "web"


urlpatterns = [
   path('', views.index, name="index"),   
   path('login/', views.login, name="login"),
   path('register/', views.register, name="register"),
   path('logout/', views.logout, name="logout"),
   path('restaurants/<int:id>/', views.restaurants, name="restaurants"),
   
   path('single_restaurant/<int:id>/', views.single_restaurant, name="single_restaurant"),
   path('single_restaurant/cart_add/<int:id>/', views.cart_add, name="cart_add"),
   path('single_restaurant/rest_cart_plus/<int:id>/', views.rest_cart_plus, name="rest_cart_plus"),
   path('single_restaurant/rest_cart_minus/<int:id>/', views.rest_cart_minus, name="rest_cart_minus"),



   path('cart/', views.cart, name="cart"),
   path('cart/cart_plus/<int:id>/', views.cart_plus, name="cart_plus"),
   path('cart/cart_minus/<int:id>/', views.cart_minus, name="cart_minus"),


   path('offers/', views.offers, name="offers"),
   path('offer/apply/<int:id>', views.offer_apply, name="offer_apply"),


   path('checkout/', views.checkout, name="checkout"),
   path('account/', views.account, name="account"),


   path('address/', views.address, name="address"),
   path('add_address/', views.add_address, name="add_address"),
   path('address/edit/<int:id>', views.edit_address, name="edit_address"),
   path('address/delete/<int:id>', views.delete_address, name="delete_address"),
   path('address/select/<int:id>', views.select_address, name="select_address"),

   path('place_order/', views.place_order, name="place_order"),

   path('orders/', views.orders, name="orders"),
   path('order_tracking/<int:id>', views.order_tracking, name="order_tracking"),
]

restaurant/models.py
from django.db import models

from users.models import User   




class StoreCategory(models.Model):
    name = models.CharField(max_length=255)
    image = models.FileField(upload_to='category')

    class Meta:
        db_table = 'restaurant_store_categoy'
        verbose_name = 'store category'
        verbose_name_plural = 'store categories'
        ordering = ['-id']

    def __str__(self):
        return self.name
    

class Store(models.Model):
    email = models.EmailField(max_length=255, unique=True)
    password = models.CharField(max_length=255)
    name = models.CharField(max_length=256)
    tagline = models.CharField(max_length=256)
    categories = models.ManyToManyField(StoreCategory, related_name="stores")
    image = models.FileField(upload_to='store')
    rating = models.FloatField()
    time = models.IntegerField()
    offer = models.CharField(max_length=255)


    class Meta:
        db_table = 'restaurant_store'
        verbose_name = 'store'
        verbose_name_plural = 'stores'
        ordering = ['-id']


    def __str__(self):
        return self.name
    


class Slider(models.Model):
    name = models.CharField(max_length=255)
    image = models.FileField(upload_to='slide')
    store = models.ForeignKey(Store, on_delete=models.CASCADE)


    class Meta:
        db_table = 'restaurant_slider'
        verbose_name = 'slider'
        verbose_name_plural = 'sliders'
        ordering = ['-id']


    def __str__(self):
        return self.name
    


    


class FoodCategory(models.Model):
    name = models.CharField(max_length=255) 
    store = models.ForeignKey(Store, on_delete=models.CASCADE) 


    class Meta:
        db_table = 'food_category'
        verbose_name = 'food category'
        verbose_name_plural = 'food categories'
        ordering = ['id']


    def __str__(self):
        return self.name
    



class FoodItem(models.Model):
    name = models.CharField(max_length=255)
    is_veg = models.BooleanField(default=False)
    price = models.IntegerField()
    image = models.FileField(upload_to='fooditems')
    categry = models.ForeignKey(FoodCategory, on_delete=models.CASCADE, related_name='fooditem')


    class Meta:
        db_table = 'food_item'
        verbose_name = 'food item'
        verbose_name_plural = 'food items'
        ordering = ['id']


    def __str__(self):
        return self.name

templates/include/footer.html
{% load static %}

<footer class="lg:hidden py-6 fixed bottom-0 z-50 bg-white w-full shadow-[0_-4px_6px_-1px_rgba(0,0,0,0.1)]">
    <section class="wrapper ">
        <div class="">
                <ul class="flex justify-center items-center">
                    <li class="mr-7"><a href="{% url 'web:index' %}" class="flex justify-start items-center text-[#515151] text-[13px] md:text-[16px]"><img src="{% static 'web/images/home.png' %}" alt="" class="w-[13px] md:w-[16px] mr-2">Home</a></li>
                    <li class="mr-7"><a href="#" class="flex justify-start items-center text-[#515151] text-[13px] md:text-[16px]"><img src="{% static 'web/images/search.png' %}" alt="" class="w-[13px] md:w-[16px] mr-2">Search</a></li>
                    <li class="mr-7"><a href="{% url 'web:cart' %}" class="flex justify-start items-center text-[#515151] text-[13px] md:text-[16px]"><img src="{% static 'web/images/bag.png' %}" alt="" class="w-[13px] md:w-[16px] mr-2">Cart</a></li>
                    <li><a href="{% url 'web:account' %}" class="flex justify-start items-center text-[#515151] text-[13px] md:text-[16px]"><img src="{% static 'web/images/user.png' %}" alt="" class="w-[13px] md:w-[16px] mr-2">Account</a></li>
                </ul>
            </div>
    </section>
</footer>

templates/include/header.html
{% load static %}

<header class="h-[80px] shadow-md">
        <section class="wrapper h-full flex justify-between items-center">
            <div>
                <img src="{% static 'web/images/logo.png' %}" alt="" class="w-[90px]">
            </div>

            <div class="hidden lg:block">
                <ul class="flex items-center">
                    <li class="mr-7"><a href="{% url 'web:index' %}" class="flex justify-start items-center text-[#515151] text-[18px]"><img src="{% static 'web/images/home.png' %}" alt="" class="w-[18px] mr-2">Home</a></li>
                    <li class="mr-7"><a href="#" class="flex justify-start items-center text-[#515151] text-[18px]"><img src="{% static 'web/images/search.png' %}" alt="" class="w-[18px] mr-2">Search</a></li>
                    <li class="mr-7"><a href="{% url 'web:cart' %}" class="flex justify-start items-center text-[#515151] text-[18px]"><img src="{% static 'web/images/bag.png' %}" alt="" class="w-[18px] mr-2">Cart</a></li>
                    <li><a href="{% url 'web:account' %}" class="flex justify-start items-center text-[#515151] text-[18px]"><img src="{% static 'web/images/user.png' %}" alt="" class="w-[18px] mr-2">Account</a></li>
                </ul>
            </div>

            <div class="flex justify-start items-center">
                <a href="" class="flex justify-start items-center mr-8">
                    <img src="{% static 'web/images/map.png' %}" alt="" class="w-[18px] mr-3">
                    <p class="text-[#515151] text-[18px] pb-1 border-b-2 border-yellow-400">Tirur, Malappuram</p>
                </a>
                <a href="{% url 'web:logout' %}">
                    <img src="{% static 'web/images/logout.png' %}" alt="" class="w-[18px] invert">
                </a>
            </div>

        </section>
    </header>

templates/include/manager-header.html
{% load static %}
   <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="" style="display: flex; justify-content: start; align-items: center;">
                    <i class="fa-solid fa-table-columns" style="font-size: 22px; color: #fff; margin-right: 20px; margin-bottom: 0.5rem; margin-left: 3px;"></i>
                    <h2 class="text-white" style="font-size: 18px;">DASHBOARD</h2>
                </a>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->

        <!--**********************************
            Header start
        ***********************************-->
        <div class="header">    
            <div class="header-content clearfix">
                
                <div class="nav-control">
                    <div class="hamburger">
                        <span class="toggle-icon"><i class="icon-menu"></i></span>
                    </div>
                </div>
                
                <div class="header-right">
                    <ul class="clearfix">
                        <li class="icons dropdown">
                            <div class="user-img c-pointer position-relative"   data-toggle="dropdown">
                                <span class="activity active"></span>
                                <img src="{% static 'images/user/form-user.png' %}" height="40" width="40" alt="">
                            </div>
                            <div class="drop-down dropdown-profile dropdown-menu">
                                <div class="dropdown-content-body">
                                    <ul>
                                        <li>
                                            <a href=""><i class="icon-user"></i> <span>Profile</span></a>
                                        </li>
                                        
                                        <hr class="my-2">
                                        <li><a href=""><i class="icon-key"></i> <span>Logout</span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="nk-sidebar">           
            <div class="nk-nav-scroll mt-2">
                <ul class="metismenu" id="menu">
                    <li>
                        <a href="{% url 'manager:dashbord' %}" aria-expanded="false">
                            <i class="fa-solid fa-house mb-1 mr-2"></i><span class="nav-text">Dashboard</span>
                        </a>
                    </li>
                    <div style="margin: 10px 14px; border-bottom: 1px solid #c8c8c8;"></div>
                    <li class="mega-menu mega-menu-sm">
                        <a  class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="fa-solid fa-store mb-1 mr-2"></i><span class="nav-text">Restaurent</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'manager:store' %}">Stores</a></li>
                            <li><a href="{% url 'manager:store_category' %}">Store Categeories</a></li>
                            <li><a href="{% url 'manager:slider' %}">Sliders</a></li>
                        </ul>
                    </li>
                    <!-- <li>
                        <a href="" aria-expanded="false">
                            <i class="fa-solid fa-square-poll-vertical mb-1 mr-2"></i><span class="nav-text">Orders</span>
                        </a>
                    </li> -->
                    <div style="margin: 10px 14px; border-bottom: 1px solid #c8c8c8;"></div>

                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="fa-solid fa-utensils mb-1 mr-2"></i><span class="nav-text">Products</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'manager:food_category' %}">Food Catgeories</a></li>
                            <li><a href="{% url 'manager:food_item' %}">Food Items</a></li>
                        </ul>
                    </li>
                    <div style="margin: 10px 14px; border-bottom: 1px solid #c8c8c8;"></div>
                    
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="fa-solid fa-tags mb-1 mr-2"></i><span class="nav-text">Customer</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="#">Address</a></li>
                            <li><a href="#">Offers</a></li>
                        </ul>
                    </li>
                    
                    <div style="margin: 10px 14px; border-bottom: 1px solid #c8c8c8;"></div>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="fa-solid fa-user-group mb-1 mr-2"></i><span class="nav-text">Users</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="">Customers</a></li>
                            <li><a href="">Owners</a></li>
                            <li><a href="">Drivers</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <!--**********************************
            Sidebar end
        ***********************************-->

templates/include/store-header.html
{% load static %}
   <!--*******************
        Preloader start
    ********************-->
    <div id="preloader">
        <div class="loader">
            <svg class="circular" viewBox="25 25 50 50">
                <circle class="path" cx="50" cy="50" r="20" fill="none" stroke-width="3" stroke-miterlimit="10" />
            </svg>
        </div>
    </div>
    <!--*******************
        Preloader end
    ********************-->

    
    <!--**********************************
        Main wrapper start
    ***********************************-->
    <div id="main-wrapper">

        <!--**********************************
            Nav header start
        ***********************************-->
        <div class="nav-header">
            <div class="brand-logo">
                <a href="" style="display: flex; justify-content: start; align-items: center;">
                    <i class="fa-solid fa-table-columns" style="font-size: 22px; color: #fff; margin-right: 20px; margin-bottom: 0.5rem; margin-left: 3px;"></i>
                    <h2 class="text-white" style="font-size: 18px;">DASHBOARD</h2>
                </a>
            </div>
        </div>
        <!--**********************************
            Nav header end
        ***********************************-->

        <!--**********************************
            Header start
        ***********************************-->
        <div class="header">    
            <div class="header-content clearfix">
                
                <div class="nav-control">
                    <div class="hamburger">
                        <span class="toggle-icon"><i class="icon-menu"></i></span>
                    </div>
                </div>
                
                <div class="header-right">
                    <ul class="clearfix">
                        <li class="icons dropdown">
                            <div class="user-img c-pointer position-relative"   data-toggle="dropdown">
                                <span class="activity active"></span>
                                <img src="{% static 'images/user/form-user.png' %}" height="40" width="40" alt="">
                            </div>
                            <div class="drop-down dropdown-profile dropdown-menu">
                                <div class="dropdown-content-body">
                                    <ul>
                                        <li>
                                            <a href=""><i class="icon-user"></i> <span>Profile</span></a>
                                        </li>
                                        
                                        <hr class="my-2">
                                        <li><a href=""><i class="icon-key"></i> <span>Logout</span></a></li>
                                    </ul>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <!--**********************************
            Header end ti-comment-alt
        ***********************************-->

        <!--**********************************
            Sidebar start
        ***********************************-->
        <div class="nk-sidebar">           
            <div class="nk-nav-scroll mt-2">
                <ul class="metismenu" id="menu">
                    <li>
                        <a href="{% url 'manager:dashbord' %}" aria-expanded="false">
                            <i class="fa-solid fa-house mb-1 mr-2"></i><span class="nav-text">Dashboard</span>
                        </a>
                    </li>
                    <div style="margin: 10px 14px; border-bottom: 1px solid #c8c8c8;"></div>
                    <li class="mega-menu mega-menu-sm">
                        <a  class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="fa-solid fa-store mb-1 mr-2"></i><span class="nav-text">Restaurent</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'manager:store' %}">Stores</a></li>
                            <li><a href="{% url 'manager:store_category' %}">Store Categeories</a></li>
                            <li><a href="{% url 'manager:slider' %}">Sliders</a></li>
                        </ul>
                    </li>
                    <!-- <li>
                        <a href="" aria-expanded="false">
                            <i class="fa-solid fa-square-poll-vertical mb-1 mr-2"></i><span class="nav-text">Orders</span>
                        </a>
                    </li> -->
                    <div style="margin: 10px 14px; border-bottom: 1px solid #c8c8c8;"></div>

                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="fa-solid fa-utensils mb-1 mr-2"></i><span class="nav-text">Products</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="{% url 'manager:food_category' %}">Food Catgeories</a></li>
                            <li><a href="{% url 'manager:food_item' %}">Food Items</a></li>
                        </ul>
                    </li>
                    <div style="margin: 10px 14px; border-bottom: 1px solid #c8c8c8;"></div>
                    
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="fa-solid fa-tags mb-1 mr-2"></i><span class="nav-text">Customer</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="#">Address</a></li>
                            <li><a href="#">Offers</a></li>
                        </ul>
                    </li>
                    
                    <div style="margin: 10px 14px; border-bottom: 1px solid #c8c8c8;"></div>
                    <li class="mega-menu mega-menu-sm">
                        <a class="has-arrow" href="javascript:void()" aria-expanded="false">
                            <i class="fa-solid fa-user-group mb-1 mr-2"></i><span class="nav-text">Users</span>
                        </a>
                        <ul aria-expanded="false">
                            <li><a href="">Customers</a></li>
                            <li><a href="">Owners</a></li>
                            <li><a href="">Drivers</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
        <!--**********************************
            Sidebar end
        ***********************************-->